version: '3.8'
services:
  nextjs:
    container_name: nextjs-ecommerce
    image: node:18
    volumes:
      - .:/ My-Folder
    working_dir: / My-Folder
    ports:
      - 3000:3000
    command: >
      bash -c "
        npm install &&
        npm run dev
      "